### ISSUE TITLE
Aye my minecraft keep crashing when it's starting up

### ISSUE THREAD

**Issue by Hello261** [gegy1000/JurassiCraft2#132]
When i take out Jurassicraft 2.0.5 out of my mods folder it works perfectly fine with LLibrary 1.7.3 and up.When i have Jurassicraft 2.0.5 and LLibrary 1.7.3 it just crashes.... Help :(

Crash Report=

---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-1.7.3-1.11.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 2/5/17 12:11 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from JurassiCraft (jurassicraft)
Caused by: java.lang.NoSuchMethodError: net.minecraftforge.common.BiomeDictionary.getBiomes(Lnet/minecraftforge/common/BiomeDictionary$Type;)Ljava/util/Set;
	at org.jurassicraft.server.dinosaur.BrachiosaurusDinosaur.<init>(BrachiosaurusDinosaur.java:33)
	at org.jurassicraft.server.entity.EntityHandler.<clinit>(EntityHandler.java:33)
	at org.jurassicraft.server.proxy.ServerProxy.onPreInit(ServerProxy.java:68)
	at org.jurassicraft.client.proxy.ClientProxy.onPreInit(ClientProxy.java:68)
	at org.jurassicraft.JurassiCraft.onPreInit(JurassiCraft.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:614)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:263)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:438)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:350)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11
	Operating System: Mac OS X (x86_64) version 10.10
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 118006080 bytes (112 MB) / 411512832 bytes (392 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.35 Powered by Forge 13.19.0.2157 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11-13.19.0.2157.jar) 
	UCH	forge{13.19.0.2157} [Minecraft Forge] (forge-1.11-13.19.0.2157.jar) 
	UCH	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.jar) 
	UCH	llibrary{1.7.3} [LLibrary] (llibrary-1.7.3-1.11.jar) 
	UCE	jurassicraft{2.0.5} [JurassiCraft] (JurassiCraft-2.0.5.jar) 
	Loaded coremods (and transformers): 
llibrary (llibrary-1.7.3-1.11.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher

**Comment by gegy1000** [comment]
My guess: You are using JurassiCraft for 1.10.2

**Comment by Hello261** [comment]
No I'm using Jurassicraft for 1.11

**Comment by gegy1000** [comment]
https://minecraft.curseforge.com/projects/jurassicraft-2-0/files/2364947
