### ISSUE TITLE
1.10.2 crashing on launching MC

### ISSUE THREAD

**Issue by LordHellscream** [gegy1000/JurassiCraft2#75]
As soon as minecraft launches it crashed. 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.43-beta.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  llibrary (llibrary-1.5.0-1.10.2.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.0.jar)
Contact their authors BEFORE contacting forge

// Would you like a cupcake?

Time: 7/30/16 1:51 AM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at org.jurassicraft.server.item.DinosaurMeatItem.func_77653_i(DinosaurMeatItem.java:39)
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:503)
	at com.polipo.foundry.ItemStackKey.toString(ItemStackKey.java:139)
	at java.lang.String.valueOf(String.java:2981)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at java.util.AbstractMap.toString(AbstractMap.java:534)
	at com.polipo.foundry.FoundryRecipes$FoundryRecipe.toString(FoundryRecipes.java:79)
	at java.lang.String.valueOf(String.java:2981)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at com.polipo.foundry.FoundryRecipes.getRecipes(FoundryRecipes.java:967)
	at com.polipo.foundry.FoundryRecipes.initRecipes(FoundryRecipes.java:413)
	at com.polipo.foundry.FoundryRecipes.init(FoundryRecipes.java:130)
	at com.polipo.foundry.ModFoundry.postInit(ModFoundry.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:595)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:793)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:322)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.jurassicraft.server.item.DinosaurMeatItem.func_77653_i(DinosaurMeatItem.java:39)
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:503)
	at com.polipo.foundry.ItemStackKey.toString(ItemStackKey.java:139)
	at java.lang.String.valueOf(String.java:2981)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at java.util.AbstractMap.toString(AbstractMap.java:534)
	at com.polipo.foundry.FoundryRecipes$FoundryRecipe.toString(FoundryRecipes.java:79)
	at java.lang.String.valueOf(String.java:2981)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at com.polipo.foundry.FoundryRecipes.getRecipes(FoundryRecipes.java:967)
	at com.polipo.foundry.FoundryRecipes.initRecipes(FoundryRecipes.java:413)
	at com.polipo.foundry.FoundryRecipes.init(FoundryRecipes.java:130)
	at com.polipo.foundry.ModFoundry.postInit(ModFoundry.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:595)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:793)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:322)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 834504248 bytes (795 MB) / 1959337984 bytes (1868 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.1.2042 Optifine OptiFine_1.10.2_HD_U_C2 44 mods loaded, 44 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJ	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJ	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.1.2042.jar) 
	UCHIJ	Forge{12.18.1.2042} [Minecraft Forge] (forge-1.10.2-12.18.1.2042.jar) 
	UCHIJ	actuallyadditions{1.10.2-r56} [Actually Additions] (ActuallyAdditions-1.10.2-r56.jar) 
	UCHIJ	Chameleon{1.9.4-2.1.6} [Chameleon] (Chameleon-1.9.4-2.1.6.jar) 
	UCHIJ	chisel{MC1.9.4-0.0.6.33} [Chisel] (Chisel-MC1.9.4-0.0.6.33.jar) 
	UCHIJ	endercore{1.10.2-0.4.1.43-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.43-beta.jar) 
	UCHIJ	endercrop{1.9-1.2-1836} [Ender Crop] (endercrop-1.9.4-1.3.1.jar) 
	UCHIJ	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJ	EnderIO{1.10.2-3.0.1.77_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.77_beta.jar) 
	UCHIJ	shetiphiancore{3.3.0} [ShetiPhian-Core] (shetiphiancore-1.10.0-3.3.0.jar) 
	UCHIJ	endertanks{1.4.1} [EnderTanks] (endertanks-1.10.0-1.4.1.jar) 
	UCHIJ	enderthing{0.6.10} [Enderthing] (enderthing-1.10.2-0.6.10.jar) 
	UCHIJ	ExtendAHand{1.3} [Extend-A-Hand] (ExtendAHand-1.10.2-1.3.jar) 
	UCHIJ	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-alpha-1.0.1.jar) 
	UCHIJ	furnus{1.83} [Furnus] (Furnus-1.10.2-1.83.jar) 
	UCHIE	giacomosfoundry{1.3.5} [Giacomo's Foundry] (GiacomosFoundry1.10.2-1.3.5.jar) 
	UCHIJ	grapplemod{1.10-v7} [Grappling hook mod] (grapplemod-1.10.2-v7.jar) 
	UCHIJ	HealthBar{1.0.3} [Health Bar] (HealthBar-1.9.4-1.0.3-14.jar) 
	UCHIJ	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJ	JEI{3.7.8.234} [Just Enough Items] (jei_1.10.2-3.7.8.234.jar) 
	UCHIJ	journeymap{1.10.2-5.2.4} [JourneyMap] (journeymap-1.10.2-5.2.4-unlimited.jar) 
	UCHIJ	llibrary{1.5.0} [LLibrary] (llibrary-1.5.0-1.10.2.jar) 
	UCHIJ	jurassicraft{2.0.0} [JurassiCraft] (JurassiCraft-2.0.0.jar) 
	UCHIJ	llor{1.1.0-mc[1.9-1.10.2]} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.0-mc[1.9-1.10.2].jar) 
	UCHIJ	notenoughwands{1.3.5} [Not Enough Wands] (notenoughwands-1.9.4-1.3.5.jar) 
	UCHIJ	parachutemod{1.5.2} [Parachute Mod] (parachutemod-ng-1.10.2-1.5.2-409.jar) 
	UCHIJ	PersistentBits{1.0.3} [Persistent Bits] (PersistentBits-1.10.2-1.0.3.jar) 
	UCHIJ	progressiveautomation{1.6.49} [Progressive Automation] (ProgressiveAutomation-1.10.2-1.6.49.jar) 
	UCHIJ	RandomUtilities{3.1.1} [Random Utilities] (Random Utilities-1.9.4-3.1.1.jar) 
	UCHIJ	reborncore{2.5.5.3} [RebornCore] (RebornCore-1.10.2-2.5.5.3-universal.jar) 
	UCHIJ	reborncore-mcmultipart{2.5.5.3} [reborncore-MCMultiPart] (RebornCore-1.10.2-2.5.5.3-universal.jar) 
	UCHIJ	StorageDrawers{1.9.4-3.2.1} [Storage Drawers] (StorageDrawers-1.9.4-3.2.1.jar) 
	UCHIJ	refinedstorage{0.8.12} [Refined Storage] (refinedstorage-0.8.12.jar) 
	UCHIJ	xreliquary{1.10.2-1.3.2.434} [Reliquary] (Reliquary-1.10.2-1.3.2.434.jar) 
	UCHIJ	rftools{5.09} [RFTools] (rftools-1.10-5.09.jar) 
	UCHIJ	rftoolsdim{4.30beta46} [RFTools Dimensions] (rftoolsdim-1.10-4.30beta46.jar) 
	UCHIJ	roots{0.110} [Roots] (roots-1.10.2-0.110.0.jar) 
	UCHIJ	storagenetwork{1.12.7} [Storage Network] (StorageNetwork-1.9.4-1.12.7.jar) 
	UCHIJ	storagesilo{1.2.2} [StorageSilo] (storagesilo-1.9.4-1.2.2b.jar) 
	UCHIJ	thutcore{4.0.0} [ThutCore] (thutcore-1.10.2-4.0.0.jar) 
	UCHIJ	thuttech{3.0.6} [Thut's Tech] (thuttech-3.0.6.jar) 
	UCHIJ	ICSE{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.0.197.jar) 
	UCHIJ	wawla{2.3.0.194} [What Are We Looking At] (Wawla-1.10.2-2.3.0.197.jar) 
	Loaded coremods (and transformers): 
EnderCorePlugin (EnderCore-1.10.2-0.4.1.43-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
llibrary (llibrary-1.5.0-1.10.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.0.jar)
  shetiphian.core.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 365.19' Renderer: 'GeForce GTX 970/PCIe/SSE2'
	EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/Pak/AppData/Roaming/.minecraft/instances/Forge1.9/mods/mcjtylib-1.10-1.9.9.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/Pak/AppData/Roaming/.minecraft/instances/Forge1.9/mods/mcjtylib-1.10-1.9.9.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/Pak/AppData/Roaming/.minecraft/instances/Forge1.9/mods/mcjtylib-1.10-1.9.9.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/Pak/AppData/Roaming/.minecraft/instances/Forge1.9/mods/mcjtylib-1.10-1.9.9.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Users/Pak/AppData/Roaming/.minecraft/instances/Forge1.9/mods/mcjtylib-1.10-1.9.9.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/Pak/AppData/Roaming/.minecraft/instances/Forge1.9/mods/mcjtylib-1.10-1.9.9.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/Pak/AppData/Roaming/.minecraft/instances/Forge1.9/mods/mcjtylib-1.10-1.9.9.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/Pak/AppData/Roaming/.minecraft/instances/Forge1.9/mods/mcjtylib-1.10-1.9.9.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/Pak/AppData/Roaming/.minecraft/instances/Forge1.9/mods/mcjtylib-1.10-1.9.9.jar!/cofh/api/energy/TileEnergyHandler.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/Pak/AppData/Roaming/.minecraft/instances/Forge1.9/mods/mcjtylib-1.10-1.9.9.jar!/cofh/api/energy/TileEnergyHandler.class

	Launched Version: 1.10.2-forge1.10.2-12.18.1.2042
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.5.0 NVIDIA 365.19, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Soartex_Fanver.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-4130 CPU @ 3.40GHz
	OptiFine Version: OptiFine_1.10.2_HD_U_C2
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 365.19
	OpenGlRenderer: GeForce GTX 970/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by gegy1000** [comment]
This should be fixed in the next version.

**Comment by gegy1000** [comment]
Has 2.0.1 solved this problem?

**Comment by LordHellscream** [comment]
yes it appeared to have been fixed. thanks
